{{- range $key, $value := .Values.repositories }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  labels:
    app.kubernetes.io/name: {{ include "git-mirror.name" $ }}
    app.kubernetes.io/instance: {{ $value.name }}
spec:
  type: {{ $.Values.porter.service.type }}
  ports:
    - port: {{ $.Values.porter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app.kubernetes.io/name: {{ include "git-mirror.name" $ }}
      app.kubernetes.io/instance: {{ $value.name }}
{{- end }}
