apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "upgradeResponder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "upgradeResponder.name" . }}
    helm.sh/chart: {{ include "upgradeResponder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "upgradeResponder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "upgradeResponder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: APPLICATION_NAME
            value: {{ .Values.applicationName }}
          - name: INFLUXDB_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: influxDBUrl
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: influxDBUser
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: influxDBPassword
          - name: PORT
            value: "{{ .Values.service.port }}"
          command:
          - upgrade-responder
          args:
          - --debug
          - start
          - --application-name
          - $(APPLICATION_NAME)
          - --upgrade-response-config
          - /run/secrets/upgrade-responder-config.json
          - --influxdb-url
          - $(INFLUXDB_URL)
          - --influxdb-user
          - $(INFLUXDB_USER)
          - --influxdb-pass
          - $(INFLUXDB_PASSWORD)
          - --port
          - $(PORT)
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
          - mountPath: /run/secrets/upgrade-responder-config.json
            name: {{ include "upgradeResponder.configMapName" . }}
            subPath: upgrade-responder-config.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: {{ include "upgradeResponder.configMapName" . }}
        configMap:
          name: {{ include "upgradeResponder.configMapName" . }}
