apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "upgradeResponder.configMapName" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "upgradeResponder.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
data:
  upgrade-responder-config.json: {{ .Values.configMap.responseConfig | toYaml | indent 2 }}
