{{ if .Values.secret.managed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "upgradeResponder.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  influxDBUrl: {{ .Values.secret.influxDBUrl | b64enc | quote }}
  influxDBUser: {{ .Values.secret.influxDBUser | b64enc | quote }}
  influxDBPassword: {{ .Values.secret.influxDBPassword | b64enc | quote }}
{{ end }}
