apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "telemetry.name" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "telemetry.name" . }}-admin
    helm.sh/chart: {{ include "telemetry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-admin
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry.name" . }}-admin
      app.kubernetes.io/instance: {{ .Release.Name }}-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telemetry.name" . }}-admin
        app.kubernetes.io/instance: {{ .Release.Name }}-admin
    spec:
      containers:
      - args:
        - server
        - --xff
        env:
        - name: TELEMETRY_GA_TID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: telemetryGaTid
        - name: TELEMETRY_PG_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: telemetryPgHost
        - name: TELEMETRY_PG_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: telemetryPgPass
        - name: TELEMETRY_PG_SSL
          value: {{ .Values.telemetryPgSSL }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: telemetry
        ports:
          - name: http
            containerPort: {{ .Values.telemetryPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthcheck.html
            port: http
        readinessProbe:
          httpGet:
            path: /healthcheck.html
            port: http
        resources:
{{ toYaml .Values.resources | indent 10 }}
