{{ if .Values.secret.managed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "telemetry.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  telemetryGaTid: {{ .Values.secret.telemetryGaTid | b64enc | quote }}
  telemetryPgPass: {{ .Values.secret.telemetryPgPass | b64enc | quote }}
{{ end }}
