{{ if .Values.secret.managed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "opniUpdateResponder.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  lurInfluxUrl: {{ .Values.secret.lurInfluxUrl | b64enc | quote }}
  lurInfluxUser: {{ .Values.secret.lurInfluxUser | b64enc | quote }}
  lurInfluxPassword: {{ .Values.secret.lurInfluxPassword | b64enc | quote }}
{{ end }}
